alter session set "_oracle_script"=true;

create user HDLine identified by 1234;
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO HDLine;
ALTER USER HDLine DEFAULT TABLESPACE USERS;
ALTER USER HDLine TEMPORARY TABLESPACE TEMP;